Add files via upload
Questo codice riporta il seguente errore:

Error: Could not find or load main class IfExercises
Caused by: java.lang.ClassNotFoundException: IfExercises